import { AbilityTag, CoreContentTag, Grade, Lesson, BlockType, Language } from './types';

export const LANGUAGES: { code: Language; label: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'sv', label: 'Svenska', dir: 'ltr' },
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'ar', label: 'العربية', dir: 'rtl' },
  { code: 'uk', label: 'Українська', dir: 'ltr' },
  { code: 'ti', label: 'ትግርኛ', dir: 'ltr' },
];

export const LGR22_LABELS: Record<Language, Record<string, string>> = {
  sv: {
    [AbilityTag.ANALYSIS]: 'Analysera tekniska lösningar',
    [AbilityTag.DESIGN]: 'Utveckla lösningar',
    [AbilityTag.CONCEPTS]: 'Begrepp & uttrycksformer',
    [AbilityTag.CONSEQUENCES]: 'Värdera konsekvenser',
    [AbilityTag.DRIVERS]: 'Teknisk utveckling',
    [CoreContentTag.SOCIETY_ENV]: 'Människa, samhälle & miljö',
    [CoreContentTag.SOLUTIONS]: 'Tekniska lösningar',
    [CoreContentTag.METHODS]: 'Arbetssätt',
  },
  en: {
    [AbilityTag.ANALYSIS]: 'Analyze solutions',
    [AbilityTag.DESIGN]: 'Develop solutions',
    [AbilityTag.CONCEPTS]: 'Concepts & representations',
    [AbilityTag.CONSEQUENCES]: 'Evaluate consequences',
    [AbilityTag.DRIVERS]: 'Tech development',
    [CoreContentTag.SOCIETY_ENV]: 'Man, society & env.',
    [CoreContentTag.SOLUTIONS]: 'Technical solutions',
    [CoreContentTag.METHODS]: 'Working methods',
  },
  ar: {
    [AbilityTag.ANALYSIS]: 'تحليل الحلول التقنية',
    [AbilityTag.DESIGN]: 'تطوير الحلول',
    [AbilityTag.CONCEPTS]: 'المفاهيم والتمثيلات',
    [AbilityTag.CONSEQUENCES]: 'تقييم العواقب',
    [AbilityTag.DRIVERS]: 'التطور التقني',
    [CoreContentTag.SOCIETY_ENV]: 'الإنسان والمجتمع والبيئة',
    [CoreContentTag.SOLUTIONS]: 'الحلول التقنية',
    [CoreContentTag.METHODS]: 'طرق العمل',
  },
  uk: {
    [AbilityTag.ANALYSIS]: 'Аналіз рішень',
    [AbilityTag.DESIGN]: 'Розробка рішень',
    [AbilityTag.CONCEPTS]: 'Концепції та представлення',
    [AbilityTag.CONSEQUENCES]: 'Оцінка наслідків',
    [AbilityTag.DRIVERS]: 'Технічний розвиток',
    [CoreContentTag.SOCIETY_ENV]: 'Людина, суспільство та довкілля',
    [CoreContentTag.SOLUTIONS]: 'Технічні рішення',
    [CoreContentTag.METHODS]: 'Методи роботи',
  },
  ti: {
    [AbilityTag.ANALYSIS]: 'ቴክኒካዊ ፍታሕ ምትንታን',
    [AbilityTag.DESIGN]: 'ፍታሕ ምምዕባል',
    [AbilityTag.CONCEPTS]: 'ምርዳእ ቴክኒካዊ ቃላት',
    [AbilityTag.CONSEQUENCES]: 'ስነምግባራዊ ሳዕቤን',
    [AbilityTag.DRIVERS]: 'ቴክኒካዊ ምዕባለ',
    [CoreContentTag.SOCIETY_ENV]: 'ሰብ፣ ሕብረተሰብን ከባቢን',
    [CoreContentTag.SOLUTIONS]: 'ቴክኒካዊ ፍታሕ',
    [CoreContentTag.METHODS]: 'አገባብ አሰራርሓ',
  },
};

export const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  sv: {
    brandName: 'koda.nu lär',
    gdprFooter: 'Ingen inloggning. Ingen spårning. Ingen persondata sparas av webbplatsen.',
    lesson1Title: 'Intro till Programmering',
    lesson1Desc: 'Vi lär oss grunderna i kod med grafiska figurer.',
    labInstruction: 'Ändra siffrorna för att flytta cirkeln. Kan du göra den blå?',
    // CommandLab translations
    jsCode: 'Javascript Kod',
    parameters: 'Parametrar',
    decreaseText: 'Minska text',
    increaseText: 'Öka text',
    canvasLabel: 'KANVAS',
    colorPalette: 'Färgpalett',
    copied: 'Kopierad!',
    copy: 'Kopiera',
    // Parameter translations
    param_x: 'x', param_y: 'y', param_r: 'radie', param_w: 'bredd', param_h: 'höjd',
    param_deg: 'vinkel', param_th: 'tjocklek', param_color: 'färg', param_size: 'storlek',
    param_msg: 'textsträng', param_x1: 'x1', param_y1: 'y1', param_x2: 'x2',
    param_y2: 'y2', param_x3: 'x3', param_y3: 'y3',
    // Existing
    dashboard: 'Lärarpanel',
    newLesson: 'Ny lektion',
    students: 'Elevvy',
    settings: 'Inställningar',
    diagnostics: 'Diagnostik',
    grade: 'Årskurs',
    lgrTags: 'Koppling till Lgr22',
    publish: 'Publicera',
    edit: 'Redigera',
    preview: 'Förhandsgranska',
    save: 'Spara',
    addBlock: 'Lägg till innehåll',
    textBlock: 'Textavsnitt',
    quizBlock: 'Quiz',
    labBlock: 'Programmeringslabb',
    imgBlock: 'Bild',
    readAloud: 'Läs upp',
    runCode: 'Kör kod',
    reset: 'Återställ',
    correct: 'Rätt!',
    incorrect: 'Försök igen.',
    coverage: 'Täckning Lgr22',
    delete: 'Radera',
    lessonTitle: 'Lektionsrubrik',
    description: 'Beskrivning',
    blockEditor: 'Innehållsredigerare',
    enterCode: 'Skriv din kod här...',
    circleLab: 'Cirkel-labb',
    rectLab: 'Rektangel-labb',
  },
  en: {
    brandName: 'koda.nu learn',
    gdprFooter: 'No login. No tracking. No personal data is saved by this website.',
    lesson1Title: 'Intro to Programming',
    lesson1Desc: 'We learn the basics of code with graphic shapes.',
    labInstruction: 'Change the numbers to move the circle. Can you make it blue?',
    // CommandLab translations
    jsCode: 'Javascript Code',
    parameters: 'Parameters',
    decreaseText: 'Decrease text size',
    increaseText: 'Increase text size',
    canvasLabel: 'CANVAS',
    colorPalette: 'Color Palette',
    copied: 'Copied!',
    copy: 'Copy',
    // Parameter translations
    param_x: 'x', param_y: 'y', param_r: 'radius', param_w: 'width', param_h: 'height',
    param_deg: 'angle', param_th: 'thickness', param_color: 'color', param_size: 'size',
    param_msg: 'text string', param_x1: 'x1', param_y1: 'y1', param_x2: 'x2',
    param_y2: 'y2', param_x3: 'x3', param_y3: 'y3',
    // Existing
    dashboard: 'Teacher Dashboard',
    newLesson: 'New Lesson',
    students: 'Student View',
    settings: 'Settings',
    diagnostics: 'Diagnostics',
    grade: 'Grade',
    lgrTags: 'Lgr22 Alignment',
    publish: 'Publish',
    edit: 'Edit',
    preview: 'Preview',
    save: 'Save',
    addBlock: 'Add Content',
    textBlock: 'Text Section',
    quizBlock: 'Quiz',
    labBlock: 'Coding Lab',
    imgBlock: 'Image',
    readAloud: 'Read Aloud',
    runCode: 'Run Code',
    reset: 'Reset',
    correct: 'Correct!',
    incorrect: 'Try again.',
    coverage: 'Lgr22 Coverage',
    delete: 'Delete',
    lessonTitle: 'Lesson Title',
    description: 'Description',
    blockEditor: 'Content Editor',
    enterCode: 'Enter code here...',
    circleLab: 'Circle Lab',
    rectLab: 'Rectangle Lab',
  },
  ar: {
    brandName: 'koda.nu تعلم',
    gdprFooter: 'لا تسجيل دخول. لا تتبع. لا يتم حفظ بيانات شخصية بواسطة الموقع.',
    lesson1Title: 'مقدمة في البرمجة',
    lesson1Desc: 'نتعلم أساسيات الكود باستخدام الأشكال الرسومية.',
    labInstruction: 'غير الأرقام لتحريك الدائرة. هل يمكنك جعلها زرقاء؟',
    // CommandLab translations
    jsCode: 'كود جافا سكريبت',
    parameters: 'المعاملات',
    decreaseText: 'تصغير النص',
    increaseText: 'تكبير النص',
    canvasLabel: 'لوحة الرسم',
    colorPalette: 'لوحة الألوان',
    copied: 'تم النسخ!',
    copy: 'نسخ',
    // Parameter translations
    param_x: 'x', param_y: 'y', param_r: 'نصف القطر', param_w: 'عرض', param_h: 'ارتفاع',
    param_deg: 'زاوية', param_th: 'سماكة', param_color: 'لون', param_size: 'حجم',
    param_msg: 'نص', param_x1: 'x1', param_y1: 'y1', param_x2: 'x2',
    param_y2: 'y2', param_x3: 'x3', param_y3: 'y3',
    // Existing
    dashboard: 'لوحة المعلم',
    newLesson: 'درس جديد',
    students: 'عرض الطالب',
    settings: 'الإعدادات',
    diagnostics: 'التشخيص',
    grade: 'الدرجة',
    lgrTags: 'محاذاة المنهج',
    publish: 'نشر',
    edit: 'تعديل',
    preview: 'معاينة',
    save: 'حفظ',
    addBlock: 'إضافة محتوى',
    textBlock: 'نص',
    quizBlock: 'اختبار قصير',
    labBlock: 'مختبر البرمجة',
    imgBlock: 'صورة',
    readAloud: 'قراءة بصوت عال',
    runCode: 'تشغيل الكود',
    reset: 'إعادة تعيين',
    correct: 'صحيح!',
    incorrect: 'حاول مرة أخرى.',
    coverage: 'تغطية المنهج',
    delete: 'حذف',
    lessonTitle: 'عنوان الدرس',
    description: 'الوصف',
    blockEditor: 'محرر المحتوى',
    enterCode: 'أدخل الكود هنا...',
    circleLab: 'مختبر الدائرة',
    rectLab: 'مختبر المستطيل',
  },
  uk: {
    brandName: 'koda.nu навчання',
    gdprFooter: 'Без логіну. Без відстеження. Сайт не зберігає персональні дані.',
    lesson1Title: 'Вступ до програмування',
    lesson1Desc: 'Ми вивчаємо основи коду за допомогою графічних фігур.',
    labInstruction: 'Змініть числа, щоб перемістити коло. Чи можете ви зробити його синім?',
    // CommandLab translations
    jsCode: 'JavaScript код',
    parameters: 'Параметри',
    decreaseText: 'Зменшити текст',
    increaseText: 'Збільшити текст',
    canvasLabel: 'ПОЛОТНО',
    colorPalette: 'Палітра кольорів',
    copied: 'Скопійовано!',
    copy: 'Копіювати',
    // Parameter translations
    param_x: 'x', param_y: 'y', param_r: 'радіус', param_w: 'ширина', param_h: 'висота',
    param_deg: 'кут', param_th: 'товщина', param_color: 'колір', param_size: 'розмір',
    param_msg: 'текст', param_x1: 'x1', param_y1: 'y1', param_x2: 'x2',
    param_y2: 'y2', param_x3: 'x3', param_y3: 'y3',
    // Existing
    dashboard: 'Панель вчителя',
    newLesson: 'Новий урок',
    students: 'Вигляд учня',
    settings: 'Налаштування',
    diagnostics: 'Діагностика',
    grade: 'Клас',
    lgrTags: 'Відповідність Lgr22',
    publish: 'Опублікувати',
    edit: 'Редагувати',
    preview: 'Попередній перегляд',
    save: 'Зберегти',
    addBlock: 'Додати вміст',
    textBlock: 'Текстовий блок',
    quizBlock: 'Вікторина',
    labBlock: 'Лабораторія коду',
    imgBlock: 'Зображення',
    readAloud: 'Читати вголос',
    runCode: 'Запустити код',
    reset: 'Скинути',
    correct: 'Правильно!',
    incorrect: 'Спробуйте ще раз.',
    coverage: 'Покриття Lgr22',
    delete: 'Видалити',
    lessonTitle: 'Заголовок уроку',
    description: 'Опис',
    blockEditor: 'Редактор вмісту',
    enterCode: 'Введіть код тут...',
    circleLab: 'Лабораторія кола',
    rectLab: 'Лабораторія прямокутника',
  },
  ti: {
    brandName: 'koda.nu ትምህርቲ',
    gdprFooter: 'ምንም ምእታው የለን። ምክትታል የለን። ውልቃዊ ሓበሬታ አይዕቀብን።',
    lesson1Title: 'መእተዊ ፕሮግራሚንግ',
    lesson1Desc: 'መሰረታዊ ነገራት ኮድ ብግራፊካዊ ቅርጽታት ንምሃር።',
    labInstruction: 'እቲ ክቢ ንምግዓዝ ነቶም ቁጽርታት ቀይሮም። ሰማያዊ ክትገብሮ ትኽእል ዶ?',
    // CommandLab translations
    jsCode: 'ጃቫስክሪፕት ኮድ',
    parameters: 'ፓራሜትሮች',
    decreaseText: 'ጽሑፍ አነሰ',
    increaseText: 'ጽሑፍ አብዘ',
    canvasLabel: 'ካንቫስ',
    colorPalette: 'የቀለም ሰሌዳ',
    copied: 'ተቀዲሑ!',
    copy: 'ቅዳሕ',
    // Parameter translations
    param_x: 'x', param_y: 'y', param_r: 'ራድየስ', param_w: 'ስፍሓት', param_h: 'ቁመት',
    param_deg: 'ኩርናዕ', param_th: 'ትስፊ', param_color: 'ሕብሪ', param_size: 'ግዝፊ',
    param_msg: 'ጽሑፍ', param_x1: 'x1', param_y1: 'y1', param_x2: 'x2',
    param_y2: 'y2', param_x3: 'x3', param_y3: 'y3',
    // Existing
    dashboard: 'ናይ መምህር ዳሽቦርድ',
    newLesson: 'ሓድሽ ትምህርቲ',
    students: 'ናይ ተምሃራይ ምርኢት',
    settings: 'ምምዕርራይ',
    diagnostics: 'መርመራ',
    grade: 'ክፍሊ',
    lgrTags: 'ምስ Lgr22 ምምስሳል',
    publish: 'አፓብሊሽ',
    edit: 'አርትዕ',
    preview: 'ቅድመ ምርኢት',
    save: 'ዓቅብ',
    addBlock: 'ትሕዝቶ ወስኽ',
    textBlock: 'ናይ ጽሑፍ ክፋል',
    quizBlock: 'ሕቶን መልስን',
    labBlock: 'ናይ ኮድ ላብራቶሪ',
    imgBlock: 'ስእሊ',
    readAloud: 'ዓው ኢልካ ንበብ',
    runCode: 'ኮድ ኣሰርሕ',
    reset: 'ምለስ',
    correct: 'ልክዕ!',
    incorrect: 'እንደገና ፈትን።',
    coverage: 'Lgr22 ሽፋን',
    delete: 'ደምስስ',
    lessonTitle: 'ርእሲ ትምህርቲ',
    description: 'መግለጺ',
    blockEditor: 'አሰናዳኢ ትሕዝቶ',
    enterCode: 'ኮድ ኣብዚ ጽሓፍ...',
    circleLab: 'ናይ ክቢ ላብራቶሪ',
    rectLab: 'ናይ ሬክታንግል ላብራቶሪ',
  }
};

export const INITIAL_LESSONS: Lesson[] = [
  {
    id: '1',
    title: 'Intro till Programmering', // Will be replaced by translation at runtime
    grade: Grade.SEVEN,
    description: 'Vi lär oss grunderna i kod med grafiska figurer.', // Will be replaced
    isPublished: true,
    createdAt: new Date().toISOString(),
    lgr22: {
      abilities: [AbilityTag.CONCEPTS, AbilityTag.DESIGN],
      coreContent: [CoreContentTag.METHODS]
    },
    blocks: [
      {
        id: 'b2',
        type: BlockType.COMMAND_LAB,
        instruction: 'Ändra siffrorna för att flytta cirkeln. Kan du göra den blå?', // Will be replaced
        targetCommandId: 'circle',
        initialCode: 'circle(150, 150, 50, "#ef4444");'
      }
    ]
  }
];